//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataGridWpf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Books
    {
        public string isbn { get; set; }
        public int publisher_id { get; set; }
        public string title { get; set; }
        public int pages { get; set; }
    
        public virtual Publishers Publishers { get; set; }
    }
}
